// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// PrtFstKnowledgeShelterDlg.cpp
// The dialog : PrtFstKnowledgeShelterDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Sep 2012  Creation: Code generated by the CAA wizard  xyuser
//===================================================================
#include "PrtFstKnowledgeShelterDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef PrtFstKnowledgeShelterDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
PrtFstKnowledgeShelterDlg::PrtFstKnowledgeShelterDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"PrtFstKnowledgeShelterDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION

//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
PrtFstKnowledgeShelterDlg::~PrtFstKnowledgeShelterDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION

//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void PrtFstKnowledgeShelterDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

