// COPYRIGHT Dassault Systemes 2011
//===================================================================
//
// MBDTechnicInfoDlg.cpp
// The dialog : MBDTechnicInfoDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2011  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#include "MBDTechnicInfoDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef MBDTechnicInfoDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MBDTechnicInfoDlg::MBDTechnicInfoDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"MBDTechnicInfoDlg",CATDlgWndPointerLocation|CATDlgWndAutoResize|CATDlgWndBtnClose|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               ),m_xmlPath("")
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame002 = NULL;
 _Frame004 = NULL;
 _TechnicNoteSearchPB = NULL;
 _NewNoteAddinPB = NULL;
 _Frame005 = NULL;
 _SpecialFeatureEditor = NULL;
 _FlagNoteCombo = NULL;
 _Label006 = NULL;
 _Label008 = NULL;
 _Frame003 = NULL;
 _SearchResultFrame = NULL;
 _SearchResultML = NULL;
 _InsertToGSMToolPB = NULL;
 _TechnicalNoteDetailFrame = NULL;
 _TechnicalNoteDetailEditor = NULL;
 _Frame001 = NULL;
 _TreeFrame = NULL;
 _TechnicNoteFrame = NULL;
 _TreeGSMToolNotesML = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION

 m_piTreeCtrl = NULL;

}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MBDTechnicInfoDlg::~MBDTechnicInfoDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame002 = NULL;
 _Frame004 = NULL;
 _TechnicNoteSearchPB = NULL;
 _NewNoteAddinPB = NULL;
 _Frame005 = NULL;
 _SpecialFeatureEditor = NULL;
 _FlagNoteCombo = NULL;
 _Label006 = NULL;
 _Label008 = NULL;
 _Frame003 = NULL;
 _SearchResultFrame = NULL;
 _SearchResultML = NULL;
 _InsertToGSMToolPB = NULL;
 _TechnicalNoteDetailFrame = NULL;
 _TechnicalNoteDetailEditor = NULL;
 _Frame001 = NULL;
 _TreeFrame = NULL;
 _TechnicNoteFrame = NULL;
 _TreeGSMToolNotesML = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION

 if (m_piTreeCtrl != NULL)
 {
	 m_piTreeCtrl = NULL;
 }

}



void MBDTechnicInfoDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//获得配置文件路径
XMLService::ReadTreeNodeFromXml(m_xmlPath,m_ListTreeNodeName);

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(2,1);
 SetGridColumnResizable(0,1);
 _Frame002 = new CATDlgFrame(this, "Frame002", CATDlgGridLayout);
_Frame002 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Frame002 -> SetGridRowResizable(0,1);
 _Frame002 -> SetGridColumnResizable(0,1);
 _Frame004 = new CATDlgFrame(_Frame002, "Frame004", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame004 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame004 -> SetGridColumnResizable(1,1);
 _TechnicNoteSearchPB = new CATDlgPushButton(_Frame004, "TechnicNoteSearchPB");
_TechnicNoteSearchPB -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _NewNoteAddinPB = new CATDlgPushButton(_Frame004, "NewNoteAddinPB");
_NewNoteAddinPB -> SetGridConstraints(0, 1, 1, 1, CATGRID_RIGHT|CATGRID_TOP|CATGRID_BOTTOM);
 _Frame005 = new CATDlgFrame(_Frame002, "Frame005", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame005 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _SpecialFeatureEditor = new CATDlgEditor(_Frame005, "SpecialFeatureEditor");
_SpecialFeatureEditor -> SetGridConstraints(0, 1, 1, 1, CATGRID_LEFT|CATGRID_TOP|CATGRID_BOTTOM);
 _FlagNoteCombo = new CATDlgCombo(_Frame005, "FlagNoteCombo", CATDlgCmbDropDown);
_FlagNoteCombo -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _Label006 = new CATDlgLabel(_Frame005, "Label006");
_Label006 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label008 = new CATDlgLabel(_Frame005, "Label008");
_Label008 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame003 = new CATDlgFrame(this, "Frame003", CATDlgGridLayout);
_Frame003 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Frame003 -> SetGridRowResizable(0,1);
 _Frame003 -> SetGridRowResizable(1,1);
 _Frame003 -> SetGridColumnResizable(0,1);
 _SearchResultFrame = new CATDlgFrame(_Frame003, "SearchResultFrame", CATDlgFraNoTitle|CATDlgGridLayout);
_SearchResultFrame -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _SearchResultFrame -> SetGridRowResizable(0,1);
 _SearchResultFrame -> SetGridColumnResizable(0,1);
 _SearchResultML = new CATDlgMultiList(_SearchResultFrame, "SearchResultML");
 CATUnicodeString SearchResultMLTitles [ 3 ];
 SearchResultMLTitles[0] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame003.SearchResultFrame.SearchResultML.ColumnTitle1");
 SearchResultMLTitles[1] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame003.SearchResultFrame.SearchResultML.ColumnTitle2");
 SearchResultMLTitles[2] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame003.SearchResultFrame.SearchResultML.ColumnTitle3");
 _SearchResultML -> SetColumnTitles(3, SearchResultMLTitles);
 _SearchResultML -> SetVisibleColumnCount( 3 );
_SearchResultML -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _InsertToGSMToolPB = new CATDlgPushButton(_SearchResultFrame, "InsertToGSMToolPB");
_InsertToGSMToolPB -> SetGridConstraints(1, 0, 1, 1, CATGRID_RIGHT|CATGRID_TOP|CATGRID_BOTTOM);
 _TechnicalNoteDetailFrame = new CATDlgFrame(_Frame003, "TechnicalNoteDetailFrame", CATDlgFraNoTitle|CATDlgGridLayout);
_TechnicalNoteDetailFrame -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _TechnicalNoteDetailFrame -> SetGridRowResizable(0,1);
 _TechnicalNoteDetailFrame -> SetGridColumnResizable(0,1);
 _TechnicalNoteDetailEditor = new CATDlgEditor(_TechnicalNoteDetailFrame, "TechnicalNoteDetailEditor", CATDlgEdtMultiline|CATDlgEdtReadOnly);
_TechnicalNoteDetailEditor -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame001 -> SetGridRowResizable(0,1);
 _Frame001 -> SetGridColumnResizable(1,1);
 _TreeFrame = new CATDlgFrame(_Frame001, "TreeFrame", CATDlgFraNoTitle|CATDlgGridLayout);
_TreeFrame -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _TechnicNoteFrame = new CATDlgFrame(_Frame001, "TechnicNoteFrame", CATDlgFraNoTitle|CATDlgGridLayout);
_TechnicNoteFrame -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _TechnicNoteFrame -> SetGridRowResizable(0,1);
 _TechnicNoteFrame -> SetGridColumnResizable(0,1);
 _TreeGSMToolNotesML = new CATDlgMultiList(_TechnicNoteFrame, "TreeGSMToolNotesML");
 _TreeGSMToolNotesML -> SetVisibleTextWidth(120);
 CATUnicodeString TreeGSMToolNotesMLTitles [ 3 ];
 TreeGSMToolNotesMLTitles[0] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame001.TechnicNoteFrame.TreeGSMToolNotesML.ColumnTitle1");
 TreeGSMToolNotesMLTitles[1] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame001.TechnicNoteFrame.TreeGSMToolNotesML.ColumnTitle2");
 TreeGSMToolNotesMLTitles[2] = CATMsgCatalog::BuildMessage("MBDTechnicInfoDlg", "Frame001.TechnicNoteFrame.TreeGSMToolNotesML.ColumnTitle3");
 _TreeGSMToolNotesML -> SetColumnTitles(3, TreeGSMToolNotesMLTitles);
 _TreeGSMToolNotesML -> SetVisibleColumnCount( 3 );
_TreeGSMToolNotesML -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//对话框的特殊处理
//控制mutillist显示长度
int  oHeight = 0,oWidth = 0; 
PrtService::GetWindowMaxSize(&oHeight,&oWidth );

_TreeGSMToolNotesML->SetColumnTextWidth(0,10);
_TreeGSMToolNotesML->SetColumnTextWidth(1,13);
_TreeGSMToolNotesML->SetColumnTextWidth(2,int(0.1*oWidth));

_SearchResultML->SetColumnTextWidth(0,10);
_SearchResultML->SetColumnTextWidth(1,10);
_SearchResultML->SetColumnTextWidth(2,int(0.115*oWidth));

_TechnicalNoteDetailEditor -> SetVisibleTextHeight(10);

//
_SpecialFeatureEditor->SetVisibleTextWidth(int (0.016*oWidth));
_FlagNoteCombo->SetVisibleTextWidth(int (0.016*oWidth));


//树结构控制
_TreeFrame -> SetGridRowResizable(0,1);
_TreeFrame -> SetGridColumnResizable(0,1);
m_piTreeCtrl = new CAATreeCtrl(_TreeFrame, "TreeCtrl");
m_piTreeCtrl -> SetGridConstraints(0,0,1,1,CATGRID_4SIDES);

for (int i = 1; i <= m_ListTreeNodeName.Size(); i ++)
{
	m_piTreeCtrl -> AddRootTreeNode(m_ListTreeNodeName[i], ""); 
}

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION
}


//需要在CMD调用一下
void MBDTechnicInfoDlg::GetGSMToolSpecs(CATDocument * ipDoc,CATListValCATISpecObject_var &listTreeNodeSpec)
{
	//获取所有结构树节点对应spec
	PrtService::CAAGsiSearchFeatureFromName(ipDoc, m_ListTreeNodeName,listTreeNodeSpec);
}

