// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// IMBDPrtWbAddin.h
// Definition of the interface to provide an addin for workbench MBDPrtWb
//
//===================================================================
//
// Usage notes:
// This class defines a new addin interface for the workbench 
// MBDPrtWb
//
//===================================================================
//
//  Oct 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#ifndef IMBDPrtWbAddin_H
#define IMBDPrtWbAddin_H

#include <CATIWorkbenchAddin.h>
#include "MBDPrtWb.h"

extern ExportedByMBDPrtWb IID IID_IMBDPrtWbAddin;

//-------------------------------------------------------------------------

class ExportedByMBDPrtWb IMBDPrtWbAddin : public CATIWorkbenchAddin
{
  CATDeclareInterface;
public:
};

//-------------------------------------------------------------------------

#endif
