// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// MBDPrdWbCmdHeader.h
// Specialization of the CATCommandHeader for your workshop MBDPrdWb
//
//===================================================================
//
// Usage notes:
// MBDPrdWb necessary implementation
// Do not edit this class
//
//===================================================================
//
//  Oct 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#include "CATCommandHeader.h"
MacDefineHeader( MBDPrdWbCmdHeader )

