// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// MBDGenWkbAddin.cpp
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Oct 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#include "MBDGenWkbAddin.h"

// ApplicationFrame Framework 
#include "CATCreateWorkshop.h"
// container
#include "CATCmdContainer.h"
#include "CATIAfrGeneralWksAddin.h"

#include "ktSoftwareLic.h"
#include "CATAfrCommandHeaderServices.h"



//----------------------------------------------------------------------
//声明commandHeader
//----------------------------------------------------------------------
// Creates the GlobleAddin command header class
#include "CATCommandHeader.h"
// Creates the GlobleAddin command header class
MacDeclareHeader(MBDDocTemplateHeader);//新的命令头类声明


 
CATImplementClass(MBDGenWkbAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 

//-----------------------------------------------------------------------------
// MBDGenWkbAddin : constructor
//-----------------------------------------------------------------------------
MBDGenWkbAddin::MBDGenWkbAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// MBDGenWkbAddin : destructor
//-----------------------------------------------------------------------------
MBDGenWkbAddin::~MBDGenWkbAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------


//TIE or TIEchain definitions
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(MBDGenWkbAddin);


//Methods implementation

//////////////////////////////////////////////////////////////////////////
//Methods implementation
// Creates the command headers
void MBDGenWkbAddin::CreateCommands()
{
	// CAACatalogHdr : identifier of the command header
	// CAACatalogCmd        : name of the mechanical modeler command class 
	// CAACatalogModule        : name of the module exporting the mechanical modeler command 
	// NULL                  : no argument for the CATMmuDebugCAA command class

	new MBDDocTemplateHeader("MBDAddinNewPartHdr", //命令的头指针标识  
		"MBDDocTemplate",   //添加的Module的模块名字//实现下面命令连接
		"MBDFAINewPartCmd",    //添加的命令Command名称
		(void *)NULL);

	new MBDDocTemplateHeader("MBDAddinNewPartFromHdr", //命令的头指针标识  
		"MBDDocTemplate",   //添加的Module的模块名字//实现下面命令连接
		"MBDFAINewPartFromCmd",    //添加的命令Command名称
		(void *)NULL);

	new MBDDocTemplateHeader("MBDAddinAddMBDGSMToolHdr", //命令的头指针标识  MBDAddinNewProductHdr
		"MBDDocTemplate",   //添加的Module的模块名字//实现下面命令连接
		"MBDAddGSMToolCmd",    //添加的命令Command名称
		(void *)NULL);

	new MBDDocTemplateHeader("MBDAddinNewPrdHdr", //命令的头指针标识  
		"MBDDocTemplate",   //添加的Module的模块名字//实现下面命令连接
		"MBDFAINewPrdCmd",    //添加的命令Command名称
		(void *)NULL);

	new MBDDocTemplateHeader("MBDTechnicInfoHdr", //命令的头指针标识  
		"MBDTechInfo",   //添加的Module的模块名字//实现下面命令连接
		"MBDTechnicInfoCmd",    //添加的命令Command名称
		(void *)NULL);
}


// Arranges the commands in toolbars and menubar
CATCmdContainer * MBDGenWkbAddin::CreateToolbars()
{
	// Create Toolbars for "Headers"  
	// Toolbar1
	NewAccess(CATCmdContainer,pMBDDocTemplateTlb,MBDDocTemplateTlb); // 工具条: 新建零件模板

	// Toolbar1 command starter 的内容
	NewAccess(CATCmdStarter,pMBDDocTemplateTlbStr01,MBDDocTemplateTlbStr01); // 新建part模板
	SetAccessCommand(pMBDDocTemplateTlbStr01, "MBDAddinNewPartHdr");
	SetAccessChild(pMBDDocTemplateTlb,pMBDDocTemplateTlbStr01);

	NewAccess(CATCmdStarter,pMBDDocTemplateTlbStr02,MBDDocTemplateTlbStr02); // New From已有part模板
	SetAccessCommand(pMBDDocTemplateTlbStr02, "MBDAddinNewPartFromHdr");
	SetAccessNext( pMBDDocTemplateTlbStr01,pMBDDocTemplateTlbStr02);

	NewAccess(CATCmdStarter,pMBDDocTemplateTlbStr03,MBDDocTemplateTlbStr03); // 新建product模板
	SetAccessCommand(pMBDDocTemplateTlbStr03, "MBDAddinAddMBDGSMToolHdr");
	SetAccessNext( pMBDDocTemplateTlbStr02,pMBDDocTemplateTlbStr03);

	NewAccess(CATCmdStarter,pMBDDocTemplateTlbStr04,MBDDocTemplateTlbStr04); // 新建product模板
	SetAccessCommand(pMBDDocTemplateTlbStr04, "MBDAddinNewPrdHdr");
	SetAccessNext( pMBDDocTemplateTlbStr03,pMBDDocTemplateTlbStr04);

	//NewAccess(CATCmdSeparator,pMBDSeparator01,MBDSeparator01);
	//SetAccessNext(pMBDDocTemplateTlbStr04,pMBDSeparator01); 

	//// Toolbar2 command starter 的内容
	//NewAccess(CATCmdStarter,pMBDTechnicInfoTlbStr01,MBDTechnicInfoTlbStr01); // MBD技术附注主功能界面
	//SetAccessCommand(pMBDTechnicInfoTlbStr01, "MBDTechnicInfoHdr");
	//SetAccessNext(pMBDSeparator01,pMBDTechnicInfoTlbStr01);

	AddToolbarView(pMBDDocTemplateTlb,1,Top);

	// Create new menus for "Headers"
	NewAccess(CATCmdContainer,pMBDDocTemplateMbr,MBDDocTemplateMbr); // 主空menu ,No Source files

	NewAccess(CATCmdContainer,pMBDDocTemplateMnu,MBDDocTemplateMnu); //Menu Title
	SetAccessChild(pMBDDocTemplateMbr,pMBDDocTemplateMnu);  // 主菜单: MBD Document Template

	NewAccess(CATCmdStarter,pMBDDocTemplateSnuStr01,MBDDocTemplateSnuStr01); // SubMenu Title
	SetAccessCommand(pMBDDocTemplateSnuStr01,"MBDAddinNewPartHdr");
	SetAccessChild(pMBDDocTemplateMnu,pMBDDocTemplateSnuStr01); // 二级菜单1: 新建part模板

	NewAccess(CATCmdStarter,pMBDDocTemplateSnuStr02,MBDDocTemplateSnuStr02); // SubMenu Title
	SetAccessCommand(pMBDDocTemplateSnuStr02,"MBDAddinNewPartFromHdr");
	SetAccessNext(pMBDDocTemplateSnuStr01,pMBDDocTemplateSnuStr02); // 二级菜单2: New From已有part模板

	NewAccess(CATCmdStarter,pMBDDocTemplateSnuStr03,MBDDocTemplateSnuStr03); // SubMenu Title
	SetAccessCommand(pMBDDocTemplateSnuStr03,"MBDAddinAddMBDGSMToolHdr");
	SetAccessNext(pMBDDocTemplateSnuStr02,pMBDDocTemplateSnuStr03); // 二级菜单3: 新建product模板

	NewAccess(CATCmdStarter,pMBDDocTemplateSnuStr04,MBDDocTemplateSnuStr04); // SubMenu Title
	SetAccessCommand(pMBDDocTemplateSnuStr04,"MBDAddinNewPrdHdr");
	SetAccessNext(pMBDDocTemplateSnuStr03,pMBDDocTemplateSnuStr04); // 二级菜单4: 新建product模板

	//NewAccess(CATCmdSeparator,pMBDSeparator,MBDSeparator);
	//SetAccessNext(pMBDDocTemplateSnuStr04,pMBDSeparator); 

	//NewAccess(CATCmdStarter,pMBDTechnicInfoSnuStr01,MBDTechnicInfoSnuStr01); // SubMenu Title
	//SetAccessCommand(pMBDTechnicInfoSnuStr01,"MBDTechnicInfoHdr");
	//SetAccessNext(pMBDSeparator,pMBDTechnicInfoSnuStr01); // 二级菜单5: 技术注释功能

	// Set the connection of menus and toolbars
	SetAddinMenu(pMBDDocTemplateTlb,pMBDDocTemplateMbr);//连接menu和toolbar

	return pMBDDocTemplateTlb;
}
