// COPYRIGHT Dassault Systemes 2011
//===================================================================
//
// MBDPrtAddMaterialDlg.cpp
// The dialog : MBDPrtAddMaterialDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2011  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#include "MBDPrtAddMaterialDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef MBDPrtAddMaterialDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MBDPrtAddMaterialDlg::MBDPrtAddMaterialDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"MBDPrtAddMaterialDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION

//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION


//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION


//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MBDPrtAddMaterialDlg::~MBDPrtAddMaterialDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION

//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION


//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION


//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void MBDPrtAddMaterialDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION


//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION


//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

