// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// PrtFstUpdateDlg.cpp
// The dialog : PrtFstUpdateDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2012  Creation: Code generated by the CAA wizard  xyuser
//===================================================================
#include "PrtFstUpdateDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef PrtFstUpdateDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
PrtFstUpdateDlg::PrtFstUpdateDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"PrtFstUpdateDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame002 = NULL;
 _SuccessMultiList = NULL;
 _Frame003 = NULL;
 _ErrorMultiList = NULL;
 _Frame005 = NULL;
 _ReportAndMarkPB = NULL;
 _DeleteAllErrorPB = NULL;
 _Frame006 = NULL;
 _Label007 = NULL;
 _Label008 = NULL;
 _LowerSpinner = NULL;
 _UpperSpinner = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
PrtFstUpdateDlg::~PrtFstUpdateDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame002 = NULL;
 _SuccessMultiList = NULL;
 _Frame003 = NULL;
 _ErrorMultiList = NULL;
 _Frame005 = NULL;
 _ReportAndMarkPB = NULL;
 _DeleteAllErrorPB = NULL;
 _Frame006 = NULL;
 _Label007 = NULL;
 _Label008 = NULL;
 _LowerSpinner = NULL;
 _UpperSpinner = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void PrtFstUpdateDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(0,1);
 SetGridColumnResizable(0,1);
 _Frame002 = new CATDlgFrame(this, "Frame002", CATDlgGridLayout);
_Frame002 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame002 -> SetGridRowResizable(0,1);
 _Frame002 -> SetGridColumnResizable(0,1);
 _SuccessMultiList = new CATDlgMultiList(_Frame002, "SuccessMultiList");
 _SuccessMultiList -> SetVisibleTextWidth(18);
 CATUnicodeString SuccessMultiListTitles [ 3 ];
 SuccessMultiListTitles[0] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame002.SuccessMultiList.ColumnTitle1");
 SuccessMultiListTitles[1] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame002.SuccessMultiList.ColumnTitle2");
 SuccessMultiListTitles[2] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame002.SuccessMultiList.ColumnTitle3");
 _SuccessMultiList -> SetColumnTitles(3, SuccessMultiListTitles);
 _SuccessMultiList -> SetVisibleColumnCount( 3 );
_SuccessMultiList -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame003 = new CATDlgFrame(this, "Frame003", CATDlgGridLayout);
_Frame003 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Frame003 -> SetGridRowResizable(0,1);
 _Frame003 -> SetGridColumnResizable(0,1);
 _ErrorMultiList = new CATDlgMultiList(_Frame003, "ErrorMultiList");
 CATUnicodeString ErrorMultiListTitles [ 3 ];
 ErrorMultiListTitles[0] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame003.ErrorMultiList.ColumnTitle1");
 ErrorMultiListTitles[1] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame003.ErrorMultiList.ColumnTitle2");
 ErrorMultiListTitles[2] = CATMsgCatalog::BuildMessage("PrtFstUpdateDlg", "Frame003.ErrorMultiList.ColumnTitle3");
 _ErrorMultiList -> SetColumnTitles(3, ErrorMultiListTitles);
 _ErrorMultiList -> SetVisibleColumnCount( 3 );
_ErrorMultiList -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame005 = new CATDlgFrame(this, "Frame005", CATDlgGridLayout);
_Frame005 -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _Frame005 -> SetGridColumnResizable(1,1);
 _ReportAndMarkPB = new CATDlgPushButton(_Frame005, "ReportAndMarkPB");
_ReportAndMarkPB -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _DeleteAllErrorPB = new CATDlgPushButton(_Frame005, "DeleteAllErrorPB");
_DeleteAllErrorPB -> SetGridConstraints(0, 1, 1, 1, CATGRID_LEFT|CATGRID_TOP|CATGRID_BOTTOM);
 _Frame006 = new CATDlgFrame(this, "Frame006", CATDlgGridLayout);
_Frame006 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Frame006 -> SetGridColumnResizable(1,1);
 _Label007 = new CATDlgLabel(_Frame006, "Label007");
_Label007 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label008 = new CATDlgLabel(_Frame006, "Label008");
_Label008 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LowerSpinner = new CATDlgSpinner(_Frame006, "LowerSpinner", CATDlgSpnEntry|CATDlgSpnDouble);
 //_LowerSpinner -> SetRange(0.000000, 10.000000, (float)10.000000);
_LowerSpinner -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _UpperSpinner = new CATDlgSpinner(_Frame006, "UpperSpinner", CATDlgSpnEntry|CATDlgSpnDouble);
 //_UpperSpinner -> SetRange(0.000000, 10.000000, (float)10.000000);
_UpperSpinner -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

_SuccessMultiList->SetColumnTextWidth(0,10);
_SuccessMultiList->SetColumnTextWidth(1,13);
_SuccessMultiList->SetColumnTextWidth(2,50);

_ErrorMultiList->SetColumnTextWidth(0,10);
_ErrorMultiList->SetColumnTextWidth(1,13);
_ErrorMultiList->SetColumnTextWidth(2,50);

//ÉèÖÃ²ÎÊý
double Start, End, StepMM;
Start = 0.0;
End = 1e+6;
StepMM = 0.001;
//
_LowerSpinner->SetMinMaxStep(Start, End, StepMM);
_UpperSpinner->SetMinMaxStep(Start, End, StepMM);
//
_LowerSpinner->SetUnit(CATDlgControl::Millimeter);
_UpperSpinner->SetUnit(CATDlgControl::Millimeter);

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

