// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// ktSoftwareLic.h
// Header definition of ktSoftwareLic
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Nov 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#ifndef ktSoftwareLic_H
#define ktSoftwareLic_H

#include "ktBasicService.h"
#include "CATUnicodeString.h"
#include "CATListOfCATString.h"


// 通过返回值校验授权信息
// SUCCEEDED() or FAILED
ExportedByktBasicService HRESULT ktVerifyUserLic(CATUnicodeString &ustrKTPRDNAME);

// 消息提示
ExportedByktBasicService void ShowDlgNotify(CATUnicodeString strTitle, CATUnicodeString strValue);

// 验证授权信息，控制CmdHeader显示状态
ExportedByktBasicService HRESULT CheckLicHeaderStatus(CATUnicodeString ustrKTPRDName,CATListOfCATString listCmdHeader);

//-----------------------------------------------------------------------

#endif
