// COPYRIGHT Dassault Systemes 2011
//===================================================================
//
// XMLService.h
// Header definition of XMLService
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Oct 2011  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef XMLService_H
#define XMLService_H

#include "ktXMLService.h"
#include "CATBaseUnknown.h"

#include "CATBaseUnknown.h"
#include "CATIDOMElement.h"
#include "CATIXMLDOMDocumentBuilder.h"
#include "CATIDOMDocument.h"
#include "CATListOfCATUnicodeString.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href XMLService constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new XMLService;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByktXMLService XMLService: public CATBaseUnknown
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     XMLService ();
     virtual ~XMLService ();

  // Copy constructor and equal operator
  // -----------------------------------
  XMLService (XMLService &);
  XMLService& operator=(XMLService&);

   /**
   * 创建XML文档
   */
  HRESULT CreateXMLDoc(const CATUnicodeString uXMLFileName,const CATUnicodeString uRootElemName, CATIDOMElement_var &iopRootElem);

  /**
   * 保存XML文档
   */
  HRESULT SaveXMLDoc(const CATUnicodeString uXMLFileName);

  /**
   * 向XML添加节点
   */
  HRESULT addXMLNode( const CATIDOMElement_var& pParentElem,
					  CATIDOMElement_var& iopNewElm,
					  const CATUnicodeString    uName,
					  const CATUnicodeString    uValue,
					  const CATListOfCATUnicodeString listAttNames,
					  const CATListOfCATUnicodeString listAttValues,
					  CATBoolean flagHasSon );

  static HRESULT CreateXmlDoc(CATUnicodeString iPath,CATIDOMDocument_var &iDoc,CATIXMLDOMDocumentBuilder_var & oBuilder);
  //iXPath is the path of the element to create, for example, NonSemantic/Texts/Text
  static HRESULT CreateElement(CATIDOMDocument_var &iDoc,CATUnicodeString iXPath,CATUnicodeString iContent,CATIDOMElement_var& oElement);
  static HRESULT CreateElement(CATIDOMDocument_var &iDoc,CATUnicodeString iXPath,CATUnicodeString iContent,CATListValCATUnicodeString iAttrNames,CATListValCATUnicodeString iAttrValues,CATIDOMElement_var& oElement);
  static HRESULT DeleteElements(CATIDOMDocument_var &iDoc,CATUnicodeString nodeName);
  static HRESULT ReadXml(CATUnicodeString iPath,CATIDOMDocument_var &iDoc,CATIXMLDOMDocumentBuilder_var & oBuilder);

  static HRESULT ReadXMLInfoFromFile(const CATUnicodeString &xmlPath,CATLISTV(CATUnicodeString) &ListDbName,
	  CATLISTV(CATUnicodeString) &ListDbWBSItem,
	  CATListOfInt &countNode,
	  CATLISTV(CATUnicodeString) &ListLableName,
	  CATLISTV(CATUnicodeString) &ListWBSItem,
	  CATLISTV(CATUnicodeString) &ListGSMToolName,
	  CATLISTV(CATUnicodeString) &ListGSMToolSwitch);

  static HRESULT ReadSRConfigFromFile(const CATUnicodeString &xmlPath,CATLISTV(CATUnicodeString) &ListShapeType,
	  CATLISTV(CATUnicodeString) &ListMaterial,
	  CATLISTV(CATUnicodeString) &ListGrid,
	  CATLISTV(CATUnicodeString) &ListSection,
	  CATLISTV(CATUnicodeString) &ListAnchor,
	  CATLISTV(CATUnicodeString) &ListAngle,
	  CATLISTV(CATUnicodeString) &ListOtherInfo);

  static HRESULT ReadTreeNodeFromXml(const CATUnicodeString &istrxmlPath,CATLISTV(CATUnicodeString) &oListTreeNodeName);

  static void GetListNodeFromXmlNode(CATIDOMElement_var &ParentElement,
	  CATLISTV(CATUnicodeString) &ListLableName,
	  CATLISTV(CATUnicodeString) &ListWBSItem,
	  int &count);

  //--------------------------------------------------------------
  //读取XML文件的一组函数
  //--------------------------------------------------------------
  static BOOL ReadXMLInfoFromFile( const CATUnicodeString xmlPath, CATListPV &ListStr);

  private:

	CATIXMLDOMDocumentBuilder_var	m_pXMLBuilder;
	CATIDOMDocument_var				m_pXMLDoc;

};

//-----------------------------------------------------------------------

#endif
