// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// MBDFAINewPartFromDlg.h
// The dialog : MBDFAINewPartFromDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#ifndef MBDFAINewPartFromDlg_H
#define MBDFAINewPartFromDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class MBDFAINewPartFromDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( MBDFAINewPartFromDlg, CATDlgDialog )

  public:

  MBDFAINewPartFromDlg();
  virtual ~MBDFAINewPartFromDlg();

  CATUnicodeString GetPartName();

  void Build ();


  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _Label001;
 CATDlgEditor*      _NewPartNameEditor;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
