// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework MBDPPRFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("ProcessPlatformVisu",Protected);
// END WIZARD EDITION ZONE
