// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// MBDPrtMainMaterialParamDlg.h
// The dialog : MBDPrtMainMaterialParamDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jul 2012  Creation: Code generated by the CAA wizard  WZ4
//===================================================================
#ifndef MBDPrtMainMaterialParamDlg_H
#define MBDPrtMainMaterialParamDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class MBDPrtMainMaterialParamDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( MBDPrtMainMaterialParamDlg, CATDlgDialog )

  public:

  MBDPrtMainMaterialParamDlg();
  virtual ~MBDPrtMainMaterialParamDlg();

  void Build ();


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
 CATDlgLabel*      _Label01;
 CATDlgLabel*      _Label02;
 CATDlgLabel*      _Label03;
 CATDlgSpinner*      _LengthSpinner;
 CATDlgSpinner*      _WidthSpinner;
 CATDlgSpinner*      _HeigthSpinner;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
