// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework ktSoftware
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Nov 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Public);
AddPrereqComponent("ApplicationFrame",Public);
AddPrereqComponent("MechanicalModelerUI",Public);
AddPrereqComponent("GSMInterfaces",Public);
AddPrereqComponent("DialogEngine",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("ConstraintModelerUI",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("ProductStructure",Public);
AddPrereqComponent("KnowledgeInterfaces",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("VisualizationBase",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("ConstraintModeler",Public);
AddPrereqComponent("ConstraintModelerInterfaces",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("LiteralFeatures",Public);
AddPrereqComponent("PartInterfaces",Public);
AddPrereqComponent("AutomationInterfaces",Public);
AddPrereqComponent("MeasureGeometryInterfaces",Public);
AddPrereqComponent("ProductStructureUI",Public);
AddPrereqComponent("XMLParser",Public);
AddPrereqComponent("TopologicalOperators",Public);
AddPrereqComponent("Tessellation",Public);
AddPrereqComponent("BasicTopologicalOpe",Public);
AddPrereqComponent("ProductStructureInterfaces",Public);
AddPrereqComponent("CATArrangementInterfaces",Public);
AddPrereqComponent("CATIAApplicationFrame",Public);
AddPrereqComponent("SpaceAnalysisInterfaces",Public);
// END WIZARD EDITION ZONE
