// COPYRIGHT Dassault Systemes 2011
//===================================================================
//
// PrtFstPointsCmd.h
// The state chart based command: PrtFstPointsCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Nov 2011  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef PrtFstPointsCmd_H
#define PrtFstPointsCmd_H

#include "ktPubHeaders.h"
#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "PrtFstPointsDlg.h"
#include "CATFeatureImportAgent.h"
#include "PrtFstPointRepeatPanelDlg.h"


//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class PrtFstPointsCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( PrtFstPointsCmd, CATStateCommand )

  public:

  PrtFstPointsCmd();
  virtual ~PrtFstPointsCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

  //消息框响应函数
  void OkDlgCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
  void CloseDlgCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
  //
  //安装线偏移反向按钮响应
  void OnReverseOffsetDirePBCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);  
  //参考极值点转换按钮响应
  void OnRefPointExtremityPBCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);  
  //参考中心点转换按钮响应
  void OnRefPointMiddlePBCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);  
  //参考点距离模式下反向按钮响应
  void OnDisToRefInvertPBCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);  
  //Ref End Point反向按钮响应
  void OnRefEndPointExtremityPBCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);  
  //
  //预览模式按钮
  void OnPREVIEWCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);

  //
  void ShowSeletedLine(CATDlgSelectorList* opiSL,CATListValCATISpecObject_var olstSpecs);
  //
  void ChangeOKApplyState();

  //选择
  CATBoolean ChoosePrds( void *UsefulData);
  CATBoolean ChooseCurve( void *UsefulData);
  CATBoolean ChooseSurf( void *UsefulData);
  //激活
  CATBoolean ActivePrdSL( void *UsefulData);
  CATBoolean ActiveCurveSL( void *UsefulData);
  CATBoolean ActiveSurfSL( void *UsefulData);
  //
  BOOL IsThisZPPrt(CATUnicodeString istrDocName);
  //
  void CreatePoints();

  //选择Filter
  CATBoolean SeletedIsPart(CATDialogAgent * iAgent, void * iUsefulData);
  
  private:

	  PrtFstPointsDlg *m_pDlg;
	  PrtFstPointRepeatPanelDlg *m_pRepeatPanelDlg;

	  //文档指针
	  CATDocument *m_piDoc;
	  CATUnicodeString m_strDocName;

	  //定义代理
	  CATPathElementAgent *m_piPrdAgt;
	  CATFeatureImportAgent *m_pCurveAgt,*m_pSurfAgt;
	  CATDialogAgent *m_pCurveSLAgt,*m_pSurfSLAgt,*m_piPrdSLAgt;

	  //定义数据列表环境变量
	  CATListValCATISpecObject_var m_lstSpecPrds;
	  CATListValCATISpecObject_var m_lstSpecCurves;
	  CATISpecObject_var m_SpecSurfs;

	  //
	  CATISpecObject_var m_spPointGSMTool;
	  CATISpecObject_var m_spCurvePar;
	  CATListValCATISpecObject_var m_alstSpecPoint;

	  //用户所选值
	  double m_dCurveOffsetValue,m_dPointsCount,m_dPointDistance,m_dType;

};

//----------------------------------------------------------------------

#endif
