// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// PrtFstPointRepeatPanelDlg.h
// The dialog : PrtFstPointRepeatPanelDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Mar 2013  Creation: Code generated by the CAA wizard  xyuser
//===================================================================
#ifndef PrtFstPointRepeatPanelDlg_H
#define PrtFstPointRepeatPanelDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class PrtFstPointRepeatPanelDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( PrtFstPointRepeatPanelDlg, CATDlgDialog )

  public:

  PrtFstPointRepeatPanelDlg();
  virtual ~PrtFstPointRepeatPanelDlg();

  void Build ();

  CATBoolean FstTypeComboItemCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
  
 //private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
 CATDlgSpinner*      _InstancesSpinner;
 CATDlgSpinner*      _PitchSpinner;
 CATDlgLabel*      _Label013;
 CATDlgLabel*      _Label014;
 CATDlgLabel*      _Label015;
 CATDlgCombo*      _FstTypeCombo;
 CATDlgFrame*      _Frame002;
 CATDlgLabel*      _Label011;
 CATDlgLabel*      _Label012;
 CATDlgSpinner*      _SpaceToRefEndPointSpinner;
 CATDlgEditor*      _RefEndPointExtremityEditor;
 CATDlgPushButton*      _ExtremityPB;
 CATDlgCheckButton*      _CheckB;
 CATDlgPushButton*      _PreviewPB;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


 int m_IChoosedIndex;

};

//----------------------------------------------------------------------

#endif
