// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// PrtFstKnowledgeBasedDlg.h
// The dialog : PrtFstKnowledgeBasedDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jul 2012  Creation: Code generated by the CAA wizard  xyuser
//===================================================================
#ifndef PrtFstKnowledgeBasedDlg_H
#define PrtFstKnowledgeBasedDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class PrtFstKnowledgeBasedDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( PrtFstKnowledgeBasedDlg, CATDlgDialog )

  public:

  PrtFstKnowledgeBasedDlg();
  virtual ~PrtFstKnowledgeBasedDlg();

  void Build ();

//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame001;
 CATDlgLabel*      _Label01;
 CATDlgLabel*      _Label02;
 CATDlgLabel*      _Label03;
 CATDlgLabel*      _Label04;
 CATDlgLabel*      _Label05;
 CATDlgCombo*      _Combo01;
 CATDlgCombo*      _Combo02;
 CATDlgCombo*      _Combo03;
 CATDlgEditor*      _Editor01;
 CATDlgEditor*      _Editor02;
 CATDlgPushButton*      _GoToSearchPB;
 CATDlgFrame*      _Frame002;
 CATDlgSelectorList*      _SearchResultSL;
 CATDlgFrame*      _Frame005;
 CATDlgPushButton*      _NextStepPB;
 CATDlgPushButton*      _LastStepPB;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION


//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
