// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// MBDFAINewPrdCmd.h
// The command: MBDFAINewPrdCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   COMMAND
//End CAA2 Wizard Generation Report
//
//  Apr 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#ifndef MBDFAINewPrdCmd_H
#define MBDFAINewPrdCmd_H

// ktsoftware module
#include "ktKerExcel.h"

//ktsoftware PubHeader
#include "ktPubHeaders.h"


#include "CATCommand.h"
#include "CATUnicodeString.h"
#include "CATLISTV_CATISpecObject.h"

class CATDocument;
class CATIProduct;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of System framework.
 * (consult base class description).
 */
class MBDFAINewPrdCmd: public CATCommand
{
  public:

  MBDFAINewPrdCmd();
  virtual ~MBDFAINewPrdCmd();

/**
 * Overload this method: when your command gains focus
 * <p>
 * Activates a command.
 * @param iFromClient 
 *   The command that requests to activate the current one.
 * @param iEvtDat
 *   The notification sent.
 */
   virtual CATStatusChangeRC Activate(
                            CATCommand * iFromClient,
                            CATNotification * iEvtDat);

/**
 *  Overload this method: when your command loses focus
 * <p>
 * Deactivates a command.
 * @param iFromClient 
 *   The command that takes the current active place.
 * @param iEvtDat
 *   The notification sent.
 */
   virtual CATStatusChangeRC Desactivate(
                            CATCommand * iFromClient,
                            CATNotification * iEvtDat);

/**
 *  Overload this method: when your command is canceled
 * <p>
 * Cancels a command.
 * @param iFromClient 
 *   The command that takes the current active place.
 * @param iEvtDat
 *   The notification sent.
 */
   virtual CATStatusChangeRC Cancel(
                            CATCommand * iFromClient,
                            CATNotification * iEvtDat);

   void InitialMBDInfo();
   CATLISTV(CATISpecObject_var) m_listARMInstancePrd;


private:


   CATUnicodeString _strDocType,_strDocName,_strMBDNotePartName;
   CATDocument *_piMBDNoteDoc;

};

//----------------------------------------------------------------------

#endif
