// COPYRIGHT Dassault Systemes 2010
//===================================================================
//
// MBDFAINewPartDlg.cpp
// The dialog : MBDFAINewPartDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2010  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#include "MBDFAINewPartDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef MBDFAINewPartDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MBDFAINewPartDlg::MBDFAINewPartDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"MBDFAINewPartDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Label001 = NULL;
 _NewPartNameEditor = NULL;
 _Label002 = NULL;
 _MBDTemplateTypeCombo = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MBDFAINewPartDlg::~MBDFAINewPartDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Label001 = NULL;
 _NewPartNameEditor = NULL;
 _Label002 = NULL;
 _MBDTemplateTypeCombo = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void MBDFAINewPartDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Label001 = new CATDlgLabel(this, "Label001");
_Label001 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _NewPartNameEditor = new CATDlgEditor(this, "NewPartNameEditor");
 _NewPartNameEditor -> SetVisibleTextWidth(20);
_NewPartNameEditor -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _Label002 = new CATDlgLabel(this, "Label002");
_Label002 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _MBDTemplateTypeCombo = new CATDlgCombo(this, "MBDTemplateTypeCombo", CATDlgCmbDropDown);
_MBDTemplateTypeCombo -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION
_NewPartNameEditor->SetText("New_Part");


//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION
_MBDTemplateTypeCombo->SetLine("设计零件MBD模板",0);
//_MBDTemplateTypeCombo->SetLine("对称件零件MBD模板",1);


}



CATUnicodeString MBDFAINewPartDlg::GetPartName()
{
	return _NewPartNameEditor->GetText();
}

int MBDFAINewPartDlg::GetMBDTempType()
{
	return _MBDTemplateTypeCombo->GetSelect();
}
