// COPYRIGHT Dassault Systemes 2011
//===================================================================
//
// MBDTechnicInfoSearchDlg.h
// The dialog : MBDTechnicInfoSearchDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Apr 2011  Creation: Code generated by the CAA wizard  ev5adm
//===================================================================
#ifndef MBDTechnicInfoSearchDlg_H
#define MBDTechnicInfoSearchDlg_H

//ktsoftware PubHeader
#include "ktPubHeaders.h"

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATLISTPIUnknown.h"
#include "CAATreeCtrl.h"
#include "CATListOfInt.h"
#include "CATListOfCATUnicodeString.h"


//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class MBDTechnicInfoSearchDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( MBDTechnicInfoSearchDlg, CATDlgDialog )

  public:

  MBDTechnicInfoSearchDlg();
  virtual ~MBDTechnicInfoSearchDlg();

  void Build ();

  void ChangeLableAndCombo();
  void OnTreeNodeSelect(CATCallbackEvent event, void * client, CATNotification * iNotification, CATSubscriberData data, CATCallback callback);
  void GetAllWBSItemInfo(CATLISTV(CATUnicodeString) &listStrSearchItems);
  HRESULT SetSearchItemComboList(CATListValCATUnicodeString astrKeyWords,CATDlgCombo * piDlgCombo);
  CATBoolean ComboItemSearchCB(CATCommand* cmd, CATNotification* evt, CATCommandClientData data);
  CATUnicodeString GetDatabaseWBSItemInfo();


  //protected:
  //private:

//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _DatabaseTreeFrame;
 CATDlgFrame*      _OuterFrame;
 CATDlgContainer*      _BlankContainer;
 CATDlgFrame*      _SearchItemFrame;
//END CAA2 WIZARD WIDGET DECLARATION SECTION

 CATDlgLabel* _SerialSearchLabel;
 CATDlgEditor* _SerialSearchEditor;

 CATDlgLabel* _ContentSearchLabel;
 CATDlgEditor* _ContentSearchEditor;

 //初始创建列表
 CATLISTP(IUnknown)  m_ItemLabelList;
 CATLISTP(IUnknown)  m_ItemComboList;

 //显示的控件列表
 CATLISTP(IUnknown)  m_ShowItemComboList;

 CAATreeCtrl * m_piTreeCtrl;

 CATLISTV(CATUnicodeString) ListDbName;
 CATLISTV(CATUnicodeString) ListDbWBSItem;
 CATListOfInt countNode;
 CATLISTV(CATUnicodeString) ListLableName;
 CATLISTV(CATUnicodeString) ListWBSItem;
 CATLISTV(CATUnicodeString) ListGSMToolName;
 CATLISTV(CATUnicodeString) ListGSMToolSwitch;

 //当前状态label and combo XML配置
 CATLISTV(CATUnicodeString) ListCurrentLableName;
 CATLISTV(CATUnicodeString) ListCurrentWBSItem;

 int m_NodeLocate;
 CATUnicodeString m_xmlPath;

};

//----------------------------------------------------------------------

#endif
