# COPYRIGHT Dassault Systemes 2011
#======================================================================
# Imakefile for module ktPrdService.m
#======================================================================
#
#  Oct 2011  Creation: Code generated by the CAA wizard  Administrator
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM JS0CORBA \
		CATApplicationFrame \
		CATObjectModelerBase \
		CATProductStructure1 \
		CATObjectSpecsModeler \
		CATVisualization  \
		CATGitInterfaces \
		KnowledgeItf \
		CATObjectSpecsModeler \
		CATMechanicalModeler CATMecModInterfaces \
		CATObjectSpecsModeler \
		KnowledgePubIDL CATViz \
	    CATLiteralFeatures KnowledgeItf \
	    CATPartInterfaces  \
		CATConstraintModelerItf CATConstraintModeler \
	    CATMathematics CATMathStream DI0PANV2 \
	    CATXMLParserItf CATInteractiveInterfaces \
	    CATTessellation \
		CATGeometricObjects   \
		CATCGMGeoMath \
		CATBasicTopologicalOpe \
		CATTopologicalOperators CATTopologicalObjects \ 
		CATArrangementPubIDL ProductStructurePubIDL CATArrangementItf ktPrtService
		
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
