// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// MBDPrtMainMaterialParamDlg.cpp
// The dialog : MBDPrtMainMaterialParamDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jul 2012  Creation: Code generated by the CAA wizard  WZ4
//===================================================================
#include "MBDPrtMainMaterialParamDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef MBDPrtMainMaterialParamDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MBDPrtMainMaterialParamDlg::MBDPrtMainMaterialParamDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"MBDPrtMainMaterialParamDlg",CATDlgWndModal|CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _Label01 = NULL;
 _Label02 = NULL;
 _Label03 = NULL;
 _LengthSpinner = NULL;
 _WidthSpinner = NULL;
 _HeigthSpinner = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MBDPrtMainMaterialParamDlg::~MBDPrtMainMaterialParamDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _Label01 = NULL;
 _Label02 = NULL;
 _Label03 = NULL;
 _LengthSpinner = NULL;
 _WidthSpinner = NULL;
 _HeigthSpinner = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void MBDPrtMainMaterialParamDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 SetGridRowResizable(0,1);
 SetGridColumnResizable(0,1);
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame001 -> SetGridColumnResizable(1,1);
 _Label01 = new CATDlgLabel(_Frame001, "Label01");
_Label01 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Label02 = new CATDlgLabel(_Frame001, "Label02");
_Label02 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Label03 = new CATDlgLabel(_Frame001, "Label03");
_Label03 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

_LengthSpinner = new CATDlgSpinner(_Frame001, "LengthSpinner", CATDlgSpnEntry|CATDlgSpnDouble);
_LengthSpinner -> SetFormat("%d");
_LengthSpinner -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
_WidthSpinner = new CATDlgSpinner(_Frame001, "WidthSpinner", CATDlgSpnEntry|CATDlgSpnDouble);
_WidthSpinner -> SetFormat("%d");
_WidthSpinner -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
_HeigthSpinner = new CATDlgSpinner(_Frame001, "HeigthSpinner", CATDlgSpnEntry|CATDlgSpnDouble);
_HeigthSpinner -> SetFormat("%d");
_HeigthSpinner -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);

//ÉèÖÃ²ÎÊý
double Start, End, StepMM;
Start = 0.0;
End = 1e+6;
StepMM = 0.001;
//
_LengthSpinner->SetMinMaxStep(Start, End, StepMM);
_WidthSpinner->SetMinMaxStep(Start, End, StepMM);
_HeigthSpinner->SetMinMaxStep(Start, End, StepMM);
//
_LengthSpinner->SetUnit(CATDlgControl::Millimeter);
_WidthSpinner->SetUnit(CATDlgControl::Millimeter);
_HeigthSpinner->SetUnit(CATDlgControl::Millimeter);

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

